// Copyright (c) 2026 The WAM Coin developers
// Distributed under the MIT software license, see COPYING.

#ifndef WAM_CHAINPARAMSSEEDS_H
#define WAM_CHAINPARAMSSEEDS_H
/**
 * Fixed seed nodes for WAM Coin.
 * AUTOGENERATED by contrib/seeds/generate-seeds.py -- do not edit.
 *
 * Each line is a BIP155 serialized (networkID, addr, port) tuple.
 *
 * Regenerate:
 *     python3 contrib/seeds/generate-seeds.py contrib/seeds \
 *         > src/wam/chainparamsseeds.h
 *
 * Only main and test are emitted. WAM has no testnet4 and no signet
 * of its own -- CUnusedNetParams exists only so that upstream code
 * expecting those constructors still links -- and regtest is local.
 * All three keep vFixedSeeds.clear(). Emitting an array nothing uses
 * would be a zero-length array, which is not valid ISO C++.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xa9,0x3a,0x9f,0xa5,0x25,0x53,
    0x01,0x04,0x05,0xdf,0x34,0xc8,0x25,0x53,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xa9,0x3a,0x9f,0xa5,0x4c,0x63,
    0x01,0x04,0x05,0xdf,0x34,0xc8,0x4c,0x63,
};

#endif // WAM_CHAINPARAMSSEEDS_H
